// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs1C_Y9QKKgeV-ZuGOi5RXSHWT33roOfc',
    appId: '1:1083693328344:android:c9eb80669518d13ab6b4ad',
    messagingSenderId: '1083693328344',
    projectId: 'time-tracker-flutter-3f037',
    storageBucket: 'time-tracker-flutter-3f037.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD67Vtpf6r8_Wr9gPQpJmkdV9YGCwDdOeg',
    appId: '1:1083693328344:ios:4159a6fec932c68db6b4ad',
    messagingSenderId: '1083693328344',
    projectId: 'time-tracker-flutter-3f037',
    storageBucket: 'time-tracker-flutter-3f037.appspot.com',
    iosClientId: '1083693328344-97mcrnepfeg3au2qemq7c6dpt7nlpgcs.apps.googleusercontent.com',
    iosBundleId: 'dev.molnes.timeTrackerFlutterCourse',
  );
}
